### ISSUE TITLE
VercelでJestを実行すると環境要因のエラーが発生する

### ISSUE THREAD

**Issue by yocajii** [yocajii/hamattimer#55]
```
[09:14:15.398] Cloning github.com/yocajii/hamattimer (Branch: setup-ci-test, Commit: ac16edb)
[09:14:15.763] Cloning completed: 364.539ms
[09:14:16.867] No Build Cache available
[09:14:16.902] Running "vercel build"
[09:14:17.404] Vercel CLI 28.2.2
[09:14:17.670] Installing dependencies...
[09:14:18.021] yarn install v1.22.17
[09:14:18.084] [1/4] Resolving packages...
[09:14:18.329] [2/4] Fetching packages...
[09:14:30.785] [3/4] Linking dependencies...
[09:14:37.259] [4/4] Building fresh packages...
[09:14:37.558] Done in 19.54s.
[09:14:37.584] Detected Next.js version: 12.2.5
[09:14:37.585] Running "yarn test-ci && next build"
[09:14:37.854] yarn run v1.22.17
[09:14:37.886] $ jest --ci
[09:14:38.287] info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
[09:14:38.527] warn  - Invalid next.config.js options detected: 
[09:14:38.528]   - The root value has an unexpected property, target, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
[09:14:38.529] 
[09:14:38.529] See more info here: https://nextjs.org/docs/messages/invalid-next-config
[09:14:38.529] info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
[09:14:40.279] FAIL __tests__/index.test.jsx
[09:14:40.279]   ● Home › renders a heading
[09:14:40.279] 
[09:14:40.280]     act(...) is not supported in production builds of React.
[09:14:40.280] 
[09:14:40.280]        5 | describe('Home', () => {
[09:14:40.280]        6 |   it('renders a heading', () => {
[09:14:40.280]     >  7 |     render(<Home />)
[09:14:40.280]          |           ^
[09:14:40.281]        8 |
[09:14:40.281]        9 |     const heading = screen.getByRole('heading', {
[09:14:40.281]       10 |       name: /welcome to next\.js!/i,
[09:14:40.281] 
[09:14:40.281]       at Object.<anonymous>.exports.unstable_act (node_modules/react/cjs/react.production.min.js:23:393)
[09:14:40.282]       at node_modules/@testing-library/react/dist/act-compat.js:63:25
[09:14:40.282]       at renderRoot (node_modules/@testing-library/react/dist/pure.js:159:26)
[09:14:40.282]       at render (node_modules/@testing-library/react/dist/pure.js:246:10)
[09:14:40.282]       at Object.<anonymous> (__tests__/index.test.jsx:7:11)
[09:14:40.282] 
[09:14:40.283]   ● Home › renders a heading
[09:14:40.283] 
[09:14:40.283]     act(...) is not supported in production builds of React.
[09:14:40.283] 
[09:14:40.283]       at Object.<anonymous>.exports.unstable_act (node_modules/react/cjs/react.production.min.js:23:393)
[09:14:40.284]       at node_modules/@testing-library/react/dist/act-compat.js:63:25
[09:14:40.284]       at node_modules/@testing-library/react/dist/pure.js:261:28
[09:14:40.284]       at cleanup (node_modules/@testing-library/react/dist/pure.js:257:22)
[09:14:40.284]       at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:35:25)
[09:14:40.285] 
[09:14:40.321] FAIL __tests__/snapshots.js
[09:14:40.325]   ● renders homepage unchanged
[09:14:40.325] 
[09:14:40.325]     act(...) is not supported in production builds of React.
[09:14:40.326] 
[09:14:40.326]       3 |
[09:14:40.326]       4 | it('renders homepage unchanged', () => {
[09:14:40.326]     > 5 |   const { container } = render(<Home />)
[09:14:40.326]         |                               ^
[09:14:40.326]       6 |   expect(container).toMatchSnapshot()
[09:14:40.326]       7 | })
[09:14:40.326]       8 |
[09:14:40.327] 
[09:14:40.327]       at Object.<anonymous>.exports.unstable_act (node_modules/react/cjs/react.production.min.js:23:393)
[09:14:40.327]       at node_modules/@testing-library/react/dist/act-compat.js:63:25
[09:14:40.327]       at renderRoot (node_modules/@testing-library/react/dist/pure.js:159:26)
[09:14:40.327]       at render (node_modules/@testing-library/react/dist/pure.js:246:10)
[09:14:40.327]       at Object.<anonymous> (__tests__/snapshots.js:5:31)
[09:14:40.327] 
[09:14:40.328]   ● renders homepage unchanged
[09:14:40.328] 
[09:14:40.328]     act(...) is not supported in production builds of React.
[09:14:40.328] 
[09:14:40.328]       at Object.<anonymous>.exports.unstable_act (node_modules/react/cjs/react.production.min.js:23:393)
[09:14:40.328]       at node_modules/@testing-library/react/dist/act-compat.js:63:25
[09:14:40.328]       at node_modules/@testing-library/react/dist/pure.js:261:28
[09:14:40.329]           at Array.forEach (<anonymous>)
[09:14:40.329]       at cleanup (node_modules/@testing-library/react/dist/pure.js:257:22)
[09:14:40.330]       at Object.<anonymous> (node_modules/@testing-library/react/dist/index.js:35:25)
[09:14:40.332] 
[09:14:40.378] Test Suites: 2 failed, 2 total
[09:14:40.378] Tests:       2 failed, 2 total
[09:14:40.379] Snapshots:   0 total
[09:14:40.379] Time:        1.491 s
[09:14:40.379] Ran all test suites.
[09:14:40.404] error Command failed with exit code 1.
[09:14:40.404] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[09:14:40.413] Error: Command "yarn test-ci && next build" exited with 1
```

**Comment by yocajii** [comment]
NODE_ENVがProductionになっているためと考えられる。

- [VercelでNext.jsのプロジェクトをデプロイしてみた](https://zenn.dev/nekoshita/articles/f8a737f38a5fb4)
- [act(...) is not supported in production builds of React · Discussion #35676 · vercel/next.js](https://github.com/vercel/next.js/discussions/35676)

**Comment by yocajii** [comment]
BUILD COMMANDを `env NODE_ENV=test yarn test-ci && next build` で上書きすることで回避するようにした。
