### ISSUE TITLE
テスト実行時にNextAuth.jsのエラーが発生する

### ISSUE THREAD

**Issue by yocajii** [yocajii/hamattimer#70]
- [next-auth][error][CLIENT_FETCH_ERROR] 
  - https://next-auth.js.org/errors#client_fetch_error
- [next-auth][error][CLIENT_SESSION_ERROR] 
  - https://next-auth.js.org/errors#client_session_error
```
❯ yarn test-ci
yarn run v1.22.19
$ jest --ci
info  - Loaded env from /home/yocajii/work/hamattimer/.env.test.local
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
info  - SWC minify release candidate enabled. https://nextjs.link/swcmin
  console.error
    [next-auth][error][CLIENT_FETCH_ERROR] 
    https://next-auth.js.org/errors#client_fetch_error fetch is not defined {
      error: {
        message: 'fetch is not defined',
        stack: 'ReferenceError: fetch is not defined\n' +
          '    at _callee$ (/home/yocajii/work/hamattimer/node_modules/next-auth/client/_utils.js:52:13)\n' +
          '    at call (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)\n' +
          '    at Generator.tryCatch [as _invoke] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)\n' +   
          '    at Generator._invoke [as next] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)\n' +      
          '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n' +
          '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)\n' +
          '    at _next (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7)\n' +
          '    at new Promise (<anonymous>)\n' +
          '    at /home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12\n' +
          '    at apply (/home/yocajii/work/hamattimer/node_modules/next-auth/client/_utils.js:88:21)\n' +
          '    at apply (/home/yocajii/work/hamattimer/node_modules/next-auth/client/_utils.js:24:21)\n' +
          '    at _callee2$ (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:128:40)\n' +
          '    at call (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)\n' +
          '    at Generator.tryCatch [as _invoke] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)\n' +   
          '    at Generator._invoke [as next] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)\n' +      
          '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n' +
          '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)\n' +
          '    at _next (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7)\n' +
          '    at new Promise (<anonymous>)\n' +
          '    at /home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12\n' +
          '    at apply (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:151:23)\n' +
          '    at apply (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:115:23)\n' +
          '    at getSession (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:457:22)\n' +
          '    at call (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)\n' +
          '    at Generator.tryCatch [as _invoke] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)\n' +   
          '    at Generator._invoke [as next] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)\n' +      
          '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n' +
          '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)\n' +
          '    at _next (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7)\n' +
          '    at new Promise (<anonymous>)\n' +
          '    at Object._getSession (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)\n' +
          '    at _getSession (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:503:16)\n' +
          '    at create (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:23150:26)\n' +
          '    at commitHookEffectListMount (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:24931:11)\n' +
          '    at commitPassiveMountOnFiber (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:24891:9)\n' +
          '    at commitPassiveMountEffects_complete (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:24878:7)\n' +    
          '    at commitPassiveMountEffects_begin (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:24866:3)\n' +       
          '    at commitPassiveMountEffects (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:27039:3)\n' +
          '    at flushPassiveEffectsImpl (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:26984:14)\n' +
          '    at flushPassiveEffects (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:26769:9)\n' +
          '    at callback (/home/yocajii/work/hamattimer/node_modules/react/cjs/react.development.js:2667:24)\n' +
          '    at flushActQueue (/home/yocajii/work/hamattimer/node_modules/react/cjs/react.development.js:2582:11)\n' +
          '    at actImplementation (/home/yocajii/work/hamattimer/node_modules/@testing-library/react/dist/act-compat.js:63:25)\n' +
          '    at renderRoot (/home/yocajii/work/hamattimer/node_modules/@testing-library/react/dist/pure.js:159:25)\n' +
          '    at renderRoot (/home/yocajii/work/hamattimer/node_modules/@testing-library/react/dist/pure.js:246:10)\n' +
          '    at Object.<anonymous> (/home/yocajii/work/hamattimer/__tests__/index.test.jsx:7:11)\n' +
          '    at Promise.then.completed (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/utils.js:333:28)\n' +
          '    at new Promise (<anonymous>)\n' +
          '    at callAsyncCircusFn (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/utils.js:259:10)\n' +
          '    at _callCircusTest (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/run.js:277:40)\n' +
          '    at _runTest (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/run.js:209:3)\n' +
          '    at _runTestsForDescribeBlock (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/run.js:97:9)\n' +
          '    at _runTestsForDescribeBlock (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/run.js:91:9)\n' +
          '    at run (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/run.js:31:3)\n' +
          '    at runAndTransformResultsToJestFormat (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterIn
it.js:136:21)\n' +
          '    at jestAdapter (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:65:21)\n' +
          '    at runTestInternal (/home/yocajii/work/hamattimer/node_modules/jest-runner/build/runTest.js:262:22)\n' +
          '    at runTest (/home/yocajii/work/hamattimer/node_modules/jest-runner/build/runTest.js:317:40)',
        name: 'ReferenceError'
      },
      url: '/api/auth/session',
      message: 'fetch is not defined'
    }

      at Object.error (node_modules/next-auth/utils/logger.js:46:13)
      at Object.clientLogger.<computed> [as error] (node_modules/next-auth/utils/logger.js:81:23)
      at error (node_modules/next-auth/client/_utils.js:75:20)
      at call (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
      at Generator.tryCatch [as _invoke] (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)
      at Generator._invoke [as next] (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)

  console.error
    [next-auth][error][CLIENT_SESSION_ERROR] 
    https://next-auth.js.org/errors#client_session_error fetch is not defined {
      message: 'fetch is not defined',
      stack: 'ReferenceError: fetch is not defined\n' +
        '    at Object.clientLogger.<computed> [as error] (/home/yocajii/work/hamattimer/node_modules/next-auth/utils/logger.js:99:9)\n' +
        '    at error (/home/yocajii/work/hamattimer/node_modules/next-auth/client/_utils.js:75:20)\n' +
        '    at call (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)\n' +
        '    at Generator.tryCatch [as _invoke] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)\n' +     
        '    at Generator._invoke [as next] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)\n' +        
        '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n' +
        '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)\n' +
        '    at _next (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7)\n' +
        '    at new Promise (<anonymous>)\n' +
        '    at /home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12\n' +
        '    at apply (/home/yocajii/work/hamattimer/node_modules/next-auth/client/_utils.js:88:21)\n' +
        '    at apply (/home/yocajii/work/hamattimer/node_modules/next-auth/client/_utils.js:24:21)\n' +
        '    at _callee2$ (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:128:40)\n' +
        '    at call (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)\n' +
        '    at Generator.tryCatch [as _invoke] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)\n' +     
        '    at Generator._invoke [as next] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)\n' +        
        '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n' +
        '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)\n' +
        '    at _next (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7)\n' +
        '    at new Promise (<anonymous>)\n' +
        '    at /home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12\n' +
        '    at apply (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:151:23)\n' +
        '    at apply (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:115:23)\n' +
        '    at getSession (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:457:22)\n' +
        '    at call (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)\n' +
        '    at Generator.tryCatch [as _invoke] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)\n' +     
        '    at Generator._invoke [as next] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)\n' +        
        '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)\n' +
        '    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)\n' +
        '    at _next (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7)\n' +
        '    at new Promise (<anonymous>)\n' +
        '    at Object._getSession (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)\n' +
        '    at _getSession (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:503:16)\n' +
        '    at create (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:23150:26)\n' +
        '    at commitHookEffectListMount (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:24931:11)\n' +
        '    at commitPassiveMountOnFiber (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:24891:9)\n' +
        '    at commitPassiveMountEffects_complete (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:24878:7)\n' +      
        '    at commitPassiveMountEffects_begin (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:24866:3)\n' +
        '    at commitPassiveMountEffects (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:27039:3)\n' +
        '    at flushPassiveEffectsImpl (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:26984:14)\n' +
        '    at flushPassiveEffects (/home/yocajii/work/hamattimer/node_modules/react-dom/cjs/react-dom.development.js:26769:9)\n' +
        '    at callback (/home/yocajii/work/hamattimer/node_modules/react/cjs/react.development.js:2667:24)\n' +
        '    at flushActQueue (/home/yocajii/work/hamattimer/node_modules/react/cjs/react.development.js:2582:11)\n' +
        '    at actImplementation (/home/yocajii/work/hamattimer/node_modules/@testing-library/react/dist/act-compat.js:63:25)\n' +
        '    at renderRoot (/home/yocajii/work/hamattimer/node_modules/@testing-library/react/dist/pure.js:159:25)\n' +
        '    at renderRoot (/home/yocajii/work/hamattimer/node_modules/@testing-library/react/dist/pure.js:246:10)\n' +
        '    at Object.<anonymous> (/home/yocajii/work/hamattimer/__tests__/index.test.jsx:7:11)\n' +
        '    at Promise.then.completed (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/utils.js:333:28)\n' +
        '    at new Promise (<anonymous>)\n' +
        '    at callAsyncCircusFn (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/utils.js:259:10)\n' +
        '    at _callCircusTest (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/run.js:277:40)\n' +
        '    at _runTest (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/run.js:209:3)\n' +
        '    at _runTestsForDescribeBlock (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/run.js:97:9)\n' +
        '    at _runTestsForDescribeBlock (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/run.js:91:9)\n' +
        '    at run (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/run.js:31:3)\n' +
        '    at runAndTransformResultsToJestFormat (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit
.js:136:21)\n' +
        '    at jestAdapter (/home/yocajii/work/hamattimer/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:65:21)\n' +
        '    at runTestInternal (/home/yocajii/work/hamattimer/node_modules/jest-runner/build/runTest.js:262:22)\n' +
        '    at runTest (/home/yocajii/work/hamattimer/node_modules/jest-runner/build/runTest.js:317:40)',
      name: 'ReferenceError'
    }

      at Object.error (node_modules/next-auth/utils/logger.js:46:13)
      at Object.clientLogger.<computed> [as error] (node_modules/next-auth/utils/logger.js:81:23)
      at error (node_modules/next-auth/react/index.js:488:22)
      at call (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
      at Generator.tryCatch [as _invoke] (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)
      at Generator._invoke [as throw] (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)

  console.error
    Warning: An update to SessionProvider inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
    
    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at children (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:416:24)
        at div
        at Home

      at call (node_modules/react-dom/cjs/react-dom.development.js:86:30)
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:60:7)
      at error (node_modules/react-dom/cjs/react-dom.development.js:27589:9)
      at warnIfUpdatesNotWrappedWithActDEV (node_modules/react-dom/cjs/react-dom.development.js:25508:5)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:17527:7)
      at setLoading (node_modules/next-auth/react/index.js:492:15)
      at call (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)


 RUNS  __tests__/index.test.jsx
/home/yocajii/work/hamattimer/node_modules/next-auth/utils/logger.js:96
                return fetch(url, {
                ^

ReferenceError: fetch is not defined
    at Object.clientLogger.<computed> [as error] (/home/yocajii/work/hamattimer/node_modules/next-auth/utils/logger.js:99:9)
    at error (/home/yocajii/work/hamattimer/node_modules/next-auth/react/index.js:488:22)
    at call (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:86:17)
    at Generator.tryCatch [as _invoke] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:66:24)
    at Generator._invoke [as throw] (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at asyncGeneratorStep (/home/yocajii/work/hamattimer/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by yocajii** [comment]
`.env.test.loca`は`NEXT_PUBLIC_SECRET`ではなく`SECRET`とする必要があった。
#126 にて対応済み。
